# Repository
services:
    App\Domain\Interface\LanguageRepositoryInterface:
        class: App\Infrastructure\Repository\Doctrine\LanguageRepository
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Domain\Interface\TranslationRepositoryInterface:
        class: App\Infrastructure\Repository\Doctrine\TranslationRepository
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Domain\Interface\UserRepositoryInterface:
        class: App\Infrastructure\Repository\Doctrine\UserRepository
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Domain\Interface\NotificationTypeRepositoryInterface:
        class: App\Infrastructure\Repository\Doctrine\NotificationTypeRepository
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'