lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: email
    token_ttl: 86400
    token_extractors:
        cookie:
            enabled: true
            name: bearer

        query_parameter:
            enabled: true
            name: bearer

    set_cookies:
        bearer:
            # POSSIBLE localhost settings
            # samesite: lax
            # secure: false
            samesite: none
            secure: true

    remove_token_from_body_when_cookies_used: false