language_module:
    resource: '../src/Application/Language/Controller/'
    type: attribute

translator_module:
    resource: '../src/Application/Translator/Controller/'
    type: attribute

user_module:
    resource: '../src/Application/User/Controller/'
    type: attribute

api_login_check:
    path: /api/auth/login_check