language_module:
    resource: '../src/UI/Controller/'
    type: attribute

translator_module:
    resource: '../src/UI/Controller/'
    type: attribute

user_module:
    resource: '../src/UI/Controller/'
    type: attribute

api_login_check:
    path: /api/auth/login_check