imports:
    - { resource: 'services/repositories.yaml'}
    - { resource: 'services/serializers.yaml'}
    - { resource: 'services/controllers.yaml'}
    - { resource: 'services/blacklist_manager.yaml'}
    - { resource: 'services/security.yaml'}

parameters:
    telegram.base_uri: '%env(TELEGRAM_BASE_URI)%'
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    sms.serwersms.token: '%env(SMS_SERWERSMS_TOKEN)%'
    sms.smsapi.token: '%env(SMS_SMSAPI_TOKEN)%'
    sms.default.provider: '%env(SMS_DEFAULT_PROVIDER)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Application/'
            - '../src/Domain/'
            - '../src/Infrastructure/'
            - '../src/UI/'

    App\Application\:
        resource: '../src/Application/*'
        tags: [ 'app.service' ]

    App\Domain\:
        resource: '../src/Domain/*'
        tags: [ 'app.domain' ]

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude:
            - '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests}'
        tags: [ 'app.infrastructure' ]

    App\Infrastructure\Doctrine\Persistence\Listener\TimestampListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    App\Domain\Factory\TranslationFactory:
        autowire: false
        arguments:
            $languageRepository: '@App\Infrastructure\Repository\Doctrine\LanguageRepository'

    _instanceof:
        App\Domain\Interface\Translator\TranslatorInterface:
            tags: [ 'app.translator.provider' ]
        App\Domain\Interface\Security\TokenManagerInterface:
            tags: [ 'app.token.manager' ]
        App\Domain\Interface\Security\BlacklistManagerInterface:
            tags: [ 'app.blacklist.manager' ]
        App\Domain\Interface\Notification\SmsProviderInterface:
            tags: [ 'app.sms.provider' ]
        App\Domain\Interface\Notification\NotificationProviderInterface:
            tags: [ 'app.notification.provider' ]

    App\Infrastructure\EventSubscriber\ExceptionSubscriber:
        public: true
        arguments:
            $logger: '@logger'
            $responseHelper: '@App\Infrastructure\Helper\ResponseHelper'
        tags:
            - { name: kernel.event_subscriber, priority: 200 }

    App\Infrastructure\Validator\ConstraintsValidator\CountryCodeValidator:
        tags:
            - { name: 'validator.constraint_validator' }

    App\Infrastructure\Notifier\Adapters\Providers\TelegramNotificationProvider:
        arguments:
            $baseUri: '%telegram.base_uri%'
            $botToken: '%telegram.bot_token%'

    App\Infrastructure\Notifier\Adapters\Providers\SmsProviders\SerwerSmsProvider:
        arguments:
            $token: '%sms.serwersms.token%'

    App\Infrastructure\Notifier\Adapters\Providers\SmsProviders\SmsApiProvider:
        arguments:
            $token: '%sms.smsapi.token%'

    App\Infrastructure\Notifier\Adapters\Providers\SmsNotificationProvider:
        arguments:
            $defaultProvider: '%sms.default.provider%'





