imports:
    - { resource: 'services/repositories.yaml'}
    - { resource: 'services/serializers.yaml'}

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Application/'
            - '../src/Domain/'
            - '../src/Infrastructure/'

    App\Application\:
        resource: '../src/Application/*'
        tags: [ 'app.service' ]

    App\Domain\:
        resource: '../src/Domain/*'
        tags: [ 'app.domain' ]

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude:
            - '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests}'
        tags: [ 'app.infrastructure' ]

    App\Application\Language\Controller\:
        resource: '../src/Application/Language/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Application\Translator\Controller\:
        resource: '../src/Application/Translator/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Infrastructure\Doctrine\Persistence\Listener\UpdatedAtListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    _instanceof:
        App\Application\Translator\Interface\TranslatorInterface:
            tags: ['app.translator.provider']
        App\Infrastructure\Security\Interface\TokenManagerInterface:
            tags: ['app.token.manager']
        App\Infrastructure\Security\Interface\BlacklistManagerInterface:
            tags: ['app.blacklist.manager']

    App\Infrastructure\Security\Adapter\BlacklistManager\RedisBlacklistAdapter:
        arguments:
            $redisConnectionString: '%env(REDIS_URL)%'

    app.application_jwt_authenticator:
        class: App\Infrastructure\Security\Authenticator\ApplicationJWTAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator


    # Factory
    App\Domain\Factory\TranslationFactory:
        autowire: false
        arguments: [ ]

    # Decorator
    App\Domain\Factory\Decorator\TranslationFactoryDecorator:
        autowire: false
        arguments:
           $innerFactory: '@App\Domain\Factory\TranslationFactory'
           $languageRepository: '@App\Infrastructure\Doctrine\Repository\LanguageRepository'
           $translationRepository: '@App\Infrastructure\Doctrine\Repository\TranslationRepository'

    App\Domain\Factory\Interface\TranslationFactoryInterface: '@App\Domain\Factory\Decorator\TranslationFactoryDecorator'

    App\Domain\Factory\Decorator\LanguageFactoryDecorator:
        arguments:
            $innerFactory: '@App\Domain\Factory\LanguageFactory'
            $languageRepository: '@App\Infrastructure\Doctrine\Repository\LanguageRepository'
