imports:
    - { resource: 'services/repositories.yaml'}
    - { resource: 'services/serializers.yaml'}
    - { resource: 'services/controllers.yaml'}
    - { resource: 'services/interfaces.yaml'}
    - { resource: 'services/blacklist_manager.yaml'}
    - { resource: 'services/security.yaml'}

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Application/'
            - '../src/Domain/'
            - '../src/Infrastructure/'

    App\Application\:
        resource: '../src/Application/*'
        tags: [ 'app.service' ]

    App\Domain\:
        resource: '../src/Domain/*'
        tags: [ 'app.domain' ]

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude:
            - '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests}'
        tags: [ 'app.infrastructure' ]

    App\Infrastructure\Doctrine\Persistence\Listener\UpdatedAtListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }








