App\Domain\Models\User:
    type: entity
    table: users
    id:
        id:
            associationKey: true
    embedded:
        id:
            class: App\Domain\Models\ValueObject\User\UserId
            columnPrefix: false
        username:
            class: App\Domain\Models\ValueObject\User\Username
            columnPrefix: false
        password:
            class: App\Domain\Models\ValueObject\User\Password
            columnPrefix: false
        email:
            class: App\Domain\Models\ValueObject\User\Email
            columnPrefix: false
        roles:
            class: App\Domain\Models\ValueObject\User\Roles
            columnPrefix: false

    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        notifications:
            targetEntity: Notification
            mappedBy: recipient

