name: Symfony

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read

jobs:
    symfony-pipeline:
        runs-on: ubuntu-latest
        steps:
            -   uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
                with:
                    php-version: '8.1'
            -   uses: actions/checkout@v3
            -   name: Copy and Rename .env.test to .env
                run: cp .env.test .env
            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-
            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            # - name: Create Database and load fixtures
            #   run: |
            #     mkdir -p data
            #     touch data/database.sqlite
            -   name: Check code with php-cs-fixer
                run: |
                    composer global require friendsofphp/php-cs-fixer
                    ~/.composer/vendor/bin/php-cs-fixer fix src/ --rules=@Symfony,@PSR12 --dry-run
            -   name: Execute tests (Unit and Feature tests) via PHPUnit
                # env:
                #   DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
                run: vendor/bin/phpunit
            -   name: Setup SSH Key
                uses: webfactory/ssh-agent@v0.5.3
                with:
                    ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}
            -   name: Add remote host to known_hosts
                run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
            -   name: Clone and Deploy
                run: |
                        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
                            cd ${{ secrets.APP_PATH }}
                            git clone https://github.com/qbejs/Symfony-Translation-Microservice.git .
                            cd ${{ secrets.APP_PATH }}
                            
                            docker compose -f .docker/docker-compose.yml up -d
                        "
#            -   name: Deploy
#                run: |
#                    scp -r $(pwd)/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.APP_PATH }}
#                    ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.APP_PATH }} && docker-compose -f .docker/docker-compose.yml up -d"
